PizzaDelivery/Controllers/PizzasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PizzaDelivery.DAL;
using PizzaDelivery.Models;

namespace PizzaDelivery.Controllers
{
    public class PizzasController : Controller
    {
        private PizzaDeliveryContext db = new PizzaDeliveryContext();

        // GET: Pizzas
        public ActionResult Index()
        {
            var pizza = db.Pizzas.Include(b => b.PizzasToIngredients).ToList();
            return View(pizza);
        }

        // GET: Pizzas/Create
        public ActionResult Create()
        {
            var MyViewModel = new PizzasViewModel
            {
                Ingredients = db.Ingredients.Select(c => new CheckBoxViewModel
                {
                    Id = c.IngredientID,
                    IngredientName = c.IngredientName,
                    Checked = false
                }).ToList()
            };

            return View(MyViewModel);
        }

        // POST: Pizzas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PizzasViewModel MyViewModel)
        {
            if (ModelState.IsValid)
            {
                var pizza = new Pizza
                {
                    PizzaName = MyViewModel.PizzaName,
                    Price = MyViewModel.Price,
                    PizzasToIngredients = new List<PizzaToIngredient>()
                };

                foreach (var item in MyViewModel.Ingredients.Where(c => c.Checked))
                {
                    var ingredient = new Ingredient { IngredientID = item.Id };
                    db.Ingredients.Attach(ingredient);

                    var pizzaToIngredient = new PizzaToIngredient
                    {
                        Ingredient = ingredient
                    };

                    pizza.PizzasToIngredients.Add(pizzaToIngredient);
                }

                db.Pizzas.Add(pizza);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(MyViewModel);
        }

        // GET: Pizzas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pizza pizza = db.Pizzas.Find(id);
            if (pizza == null)
            {
                return HttpNotFound();
            }
            var Results = from i in db.Ingredients
                          select new
                          {
                              i.IngredientID,
                              i.IngredientName,
                              Checked = ((from io in db.PizzasToIngredients
                                          where (io.PizzaID == id) & (io.IngredientID == i.IngredientID)
                                          select io).Count() > 0)
                          };

            var MyViewModel = new PizzasViewModel();

            MyViewModel.PizzaID = id.Value;
            MyViewModel.PizzaName = pizza.PizzaName;
            MyViewModel.Price = pizza.Price;

            var MyCheckBoxList = new List<CheckBoxViewModel>();

            foreach (var item in Results)
            {
                MyCheckBoxList.Add(new CheckBoxViewModel { Id = item.IngredientID, IngredientName = item.IngredientName, Checked = item.Checked });
            }
            MyViewModel.Ingredients = MyCheckBoxList;

            return View(MyViewModel);
        }

        // POST: Pizzas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PizzasViewModel pizza)
        {
            if (ModelState.IsValid)
            {
                var MyPizza = db.Pizzas.Find(pizza.PizzaID);
                MyPizza.PizzaName = pizza.PizzaName;
                MyPizza.Price = pizza.Price;

                foreach (var item in db.PizzasToIngredients)
                {
                    if (item.PizzaID == pizza.PizzaID)
                    {
                        db.Entry(item).State = EntityState.Deleted;
                    }

                }

                foreach (var item in pizza.Ingredients)
                {
                    if (item.Checked)
                    {
                        db.PizzasToIngredients.Add(new PizzaToIngredient() { PizzaID = pizza.PizzaID, IngredientID = item.Id });
                    }

                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pizza);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PizzaDelivery/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PizzaDelivery.Models;
using PizzaDelivery.DAL;

namespace PizzaDelivery.Controllers
{
    public class ShoppingCartController : Controller
    {
        PizzaDeliveryContext db = new PizzaDeliveryContext();

        // GET: ShoppingCart
        public ActionResult Index()
        {
            if (Session["cart"] == null)
            {
                return View("Error");
            }
            else
            {
                return View("Cart");
            }
        }

        private int isExisting(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Pizza.PizzaID == id)
                    return i;
            return -1;
        }

        public ActionResult Delete(int id)
        {
            int index = isExisting(id);
            List<Item> cart = (List<Item>)Session["cart"];
            cart.RemoveAt(index);
            Session["cart"] = cart;

            return View("Cart");
        }

        public ActionResult Delete1(int id)
        {
            int index = isExisting(id);
            List<Item> cart = (List<Item>)Session["cart"];
            cart.RemoveAt(index);
            Session["cart"] = cart;

            return RedirectToAction("Create", "Orders");
        }

        public ActionResult AddToCart(int id)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item(db.Pizzas.Find(id), 1));
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExisting(id);
                if (index == -1)
                    cart.Add(new Item(db.Pizzas.Find(id), 1));
                else
                    cart[index].Quantity++;
                Session["cart"] = cart;
            }
            return View("Cart");
        }
    }
}

PizzaDelivery/Views/ShoppingCart/Cart.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using PizzaDelivery.Models;
<br />
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover table-responsive">
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                @{double total = 0;}
                @{foreach (var item in (List<Item>)Session["cart"])
                    {
                        double subTotal = Convert.ToDouble(item.Quantity) * Convert.ToDouble(item.Pizza.Price);
                        total += subTotal;
                        <tr>
                            <td>@Html.ActionLink("Delete", "Delete", "ShoppingCart", new { id = item.Pizza.PizzaID }, null)</td>
                            <td>@item.Pizza.PizzaName</td>
                            <td>@item.Pizza.Price,- Kč</td>
                            <td>@item.Quantity</td>
                            <td>@(item.Pizza.Price * item.Quantity),- Kč</td>
                        </tr>
                    }
                }
                <tfoot>
                    <tr>
                        <td align="right" colspan="4">Sum</td>
                        <td>@total,- Kč</td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
    <div class="row">
            <div class="col-md-6">
                <button class="btn btn-default btn-primary" type="button" onclick="location.href='@Url.Action("Index", "Pizzas")'">Continue Shopping</button>
            </div>
            <div class="col-md 6">
                <button class="btn btn-default btn-primary col-md-offset-5" type="button" onclick="location.href='@Url.Action("Create", "Orders")'">Checkout</button>
            </div>
        </div>
</div>
<br />

PizzaDelivery/Views/ShoppingCart/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}